src/views/TeamCreation.vue

Implemented the logging of the JSON object in the console and made a few minor tweaks.

Team creation

---

src/views/AboutView.vue
src/views/Login.vue
src/views/MapPage.vue
src/views/SignUp.vue
src/views/TeamCreation.vue

Edited the login and sign up pages so that they are close to completion. All required fields are there, most styling is done and methods for hitting the API are in place. See screenshots below for current look.

Login and sign up pages

---

.eslintrc.js
.github/workflows/nodejs.yml
package-lock.json

console.log/console.error is fatal on build but not on serve, so our builds can't deploy that have console logs, but they should fail gracefully

Fixing a Broken Deploy

---

src/router/index.js
src/views/AvailableTeams.vue

Created the available teams page. Teams link to the team overview page and the create new team button leads to the create team page.

Available teams

---

.env.development
.env.localhost
.env.production
src/App.vue
src/api/api.js
src/auth/axiosInstance.js
src/auth/token.js
src/components/Board.vue
src/components/Header.vue
src/components/Map.vue
src/router/index.js
src/store/index.js
src/views/AvailableTeams.vue
src/views/HomeView.vue
src/views/IndividualTeamView.vue
src/views/LoginView.vue
src/views/ProfileView.vue
src/views/SignUpView.vue
src/views/TeamCreationView.vue
src/views/TeamsLeaderboardView.vue
src/views/VolunteersLeaderboardView.vue

Connecting teams and leaderboards to backend

Teams Connection

---

src/api/api.js
src/views/CurrentReservations.vue
src/views/MapView.vue

Link to trello card: [https://trello.com/c/kKjYzDyE](https://trello.com/c/kKjYzDyE)
Additionally connected making a reservation to the back end, this for testing purposes, but should be fully functional. See screenshots for look of current reservations page.

Connect current reservations

---

src/views/AvailableTeams.vue
src/views/IndividualTeamView.vue

Screenshots attached for new look, no Trello ticket

Available teams shows the users current teams and the available teams

---

src/components/Board.vue

Ticket link: [https://trello.com/c/pCyzRd9D](https://trello.com/c/pCyzRd9D)

Fixed sorting of leaderboard

---

src/components/Header.vue
src/views/TeamCreationView.vue

Ticket: [https://trello.com/c/SsXAuHwx](https://trello.com/c/SsXAuHwx)
See below for new look. Cannot figure out bug with date picker having two error symbols

Create team page tweaks

---

cypress.json
package-lock.json
package.json
tests/e2e/.eslintrc.js
tests/e2e/plugins/index.js
tests/e2e/specs/signIn.js
tests/e2e/specs/test.js
tests/e2e/support/commands.js
tests/e2e/support/index.js

Max add cypress

---

src/components/Header.vue

Ticket: [https://trello.com/c/EToOkq9N](https://trello.com/c/EToOkq9N)
Very minor change, see color below.

Changed the color of the menu button in the header

---

src/views/CompletionsOverview.vue
src/views/IndividualTeamView.vue
src/views/LeaderboardView.vue
src/views/MapView.vue
src/views/ReservationsOverview.vue
src/views/Settings.vue
src/views/TeamCreationView.vue

Added error messages for every call, removed console log, replaced alerts by toast and made every async/await .then.catch.
Ticket: [https://trello.com/c/jzLGHcgu](https://trello.com/c/jzLGHcgu)

Cleaned up code

---

package-lock.json
package.json
src/components/SelectedStreets.vue
src/views/MapView.vue

Added popover element to allow the user to remove a currently selected street

Removeable blocks

---

src/components/SelectedStreets.vue
src/views/MapView.vue

Fixed block list breaking lines unnecessarily and changed labels to be off by default

Small styling changes to map

---

src/views/Settings.vue

Changed the button colors, checked the button and their info, removed deactivate account for admins.
Ticket: [https://trello.com/c/Yq8hTthF](https://trello.com/c/Yq8hTthF)

Cleaned up the settings page

---

src/components/Header.vue
src/components/Map.vue
src/components/SelectedStreets.vue
src/views/AvailableTeams.vue
src/views/IndividualTeamView.vue
src/views/MapView.vue

Fixes some map styling with the modal, hiding the title, and action button positioning.
Change some wording in the header menu.
Fix team progress bar and trophy positioning.
Add tooltips for hiding map title and applying for team.

Fixes to map and team style

---

src/views/LoginView.vue
src/views/SignUpView.vue

Ticket: [https://trello.com/c/bwPL8jHR](https://trello.com/c/bwPL8jHR)

Login and sign up are the same size

---

src/views/AvailableTeams.vue
src/views/CompletionsOverview.vue
src/views/ReservationsOverview.vue

Ticket: [https://trello.com/c/LCRXX9WV](https://trello.com/c/LCRXX9WV)

Fixed showing id and added buttons to admin pages

---

src/components/Board.vue

Added headers to leaderboards

---

src/router/index.js
src/views/CompletionsOverview.vue
src/views/MapView.vue
src/views/ReservationsOverview.vue
src/views/TeamProgress.vue

Includes fixing navigation for admin from block overview to map.
Styling to tables to center text and add some padding.
Changing team progress highlighting to just change block completion progress.

Various fixes for admin specific pages

---

src/views/MapView.vue

Ticket: [https://trello.com/c/q1onYkSc](https://trello.com/c/q1onYkSc)
Also added similar message for unreserving and completing blocks

Added messages for reserving, unreserving and completing blocks

---

src/router/index.js
src/views/HomeView.vue
src/views/LoginView.vue
src/views/SignUpView.vue

Ticket: [https://trello.com/c/YJKtJQzu](https://trello.com/c/YJKtJQzu)
Home page now has a prop, 'firstSignIn', which if set to true will display 'Welcome user' instead of 'Welcome back, user'.

When a user sign ups, home page says 'welcome'

---

src/api/api.js
src/views/Settings.vue

- Add "Change Username" button to Settings page to allow Users to change their username

Add Setting to Change Username

---

src/components/Map.vue

PR: https://trello.com/c/QhaHieZk/79-change-default-location-to-somewhere-other-than-neu

Changed center of default location to Boston Common and zoomed out map

---

src/api/api.js
src/views/LoginView.vue

Added forgot password option on login

---

.travis.yml
package-lock.json
package.json

removed vast majority of low priority vulnerabilities and all but 1 high priority

Fix NPM Dependencies

---

src/api/api.js
src/views/Settings.vue

Creates a button for current admins to add new admins instead of having to make a direct database query.
Asks for new admin email and current admin password for verification.
https://code4community-team.monday.com/boards/702429655/pulses/716639268
Not sure if I added the routes correctly,,,

Nb.new admin button ui

---

src/auth/constants.js

Ticket: https://code4community-team.monday.com/boards/702429655/views/12631042/pulses/711883541
- Added new privilege level, and value should be read correctly from the database now

Add New Super User Privilege Level
